#!/usr/bin/env ruby
#
# frozen_string_literal: true

success = true

success &&= system(*%w[kdk start postgresql-geo])

# This creates databases, seeds, and runs migrations as needed.
# It creates khulnasofthq_geo_development but unfortunately not khulnasofthq_geo_test.
success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *%w[../support/bundle-exec rails db:prepare], chdir: 'khulnasoft')

# RAILS_ENV=test rails db:create:geo is not idempotent, and it's also not a huge deal if it fails.
system({ 'force' => 'yes', 'BOOTSTRAP' => '1', 'RAILS_ENV' => 'test' }, *%w[../support/bundle-exec rails db:create:geo], chdir: 'khulnasoft')

# To recreate the Praefect DB
success &&= system(*%w[kdk reconfigure], chdir: 'khulnasoft')

exit if success

abort "#{$PROGRAM_NAME} failed"
